language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test
  - cargo test --release
  - cargo test --features ffi --all ;
  - cargo test --features ffi --release --all ;
  - cargo test --features bindings --all ;
