[package]
name = "bvh_anim"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]
edition = "2018"
description = "Placeholder"
license = "MIT"

[dependencies]
atomic_refcell = "0.1"
lexical = "2.1"
mint = "0.5"
smallstring = "0.1"
smallvec = "0.6"

[dev-dependencies]
winit = "0.19"
wgpu = "0.2"