include_guard = "BVH_ANIM_H"
tab_width = 4
language = "C"
style = "Tag"
documentation_style = "Doxy"
header = """
/*
 *
 * The bvh_anim library, used to parse bvh files. You can view the documentation
 * for this library at <<PLACEHOLDER>>.
 *
 * Copyright (c) 2019 George Burton
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */
"""

sys_includes = ["stdio"]

autogen_warning = """
/* This file has been automatically generated - do not edit it manually. */

#if defined(__cplusplus)
#define BVH_C_API extern "C"
#else
#define BVH_C_API extern
#endif /* defined(__cplusplus) */

#if defined(_WIN32)
    #if defined(__CYGWIN__)
        #ifndef __has_attribute
            #define __has_attribute(x) 0
        #endif

        #if __has_attribute(warn_unused_result)
            #define BVH_WARN_UNUSED __attribute__((warn_unused_result))
        #else
            #define BVH_WARN_UNUSED
        #endif

        #if __has_attribute((dllimport))
            #define BVH_DLL_PUBLIC __attribute__((dllimport))
        #else
            #define BVH_DLL_PUBLIC
        #endif
    #elif defined(_MSC_VER)
        #if (_MSC_VER >= 1700)
            #define BVH_WARN_UNUSED _Check_return_
        #else
            #define BVH_WARN_UNUSED
        #endif

        #define BVH_DLL_PUBLIC __declspec(dllimport)
    #else
        #define BVH_WARN_UNUSED
        #define BVH_DLL_PUBLIC
    #endif
#else
    #ifndef __has_attribute
        #define __has_attribute(x) 0
    #endif

    #if __has_attribute(warn_unused_result)
        #define BVH_WARN_UNUSED __attribute__((warn_unused_result))
    #else
        #define BVH_WARN_UNUSED
    #endif

    #if __has_attribute(visibility)
        #define BVH_DLL_PUBLIC __attribute__((visibility ("default")))
    #else
        #define BVH_DLL_PUBLIC
    #endif
#endif

#if defined(_MSC_VER)
    #include <sal.h>
#endif
"""

[fn]
must_use = "BVH_WARN_UNUSED"
prefix = "BVH_C_API BVH_DLL_PUBLIC"

[export]
# Remove this when https://github.com/eqrion/cbindgen/pull/314 is published
exclude = ["NSEC_FACTOR"]
